### ISSUE TITLE
Configuration des rôles

### ISSUE THREAD

**Issue by shiipou** [EsupPortail/esup-stage#16]

**Comment by vdubus** [comment]
It seems that we need 7 roles:

- Student
- Teacher
- Manager
- Chef Manager 
- Administrator
- Company
- Observer

**Comment by vdubus** [comment]
# List of roles

* Student
* Referent Teacher
* Manager
* Chef Manager
* Administrator
* Company
* Observer

# Administrator

At the initialization of the application, if no administrator already are assign, it is expected to be able to access the administrator affectation page and to assign someone to this role.

Yet, because of security reason, we should avoid that and ensure that this page can only be accessed by authorized people through configuration at the start of the application.

The administrator is allow to access all pages.

# Chef Manager

The Chef Manager is the one which will assign other Chef Manager and Manager.
The Chef Manager have also the same right as the Manager.

Does that mean that a Chef Manager is allow to all Management Center?

# Manager

It seems to be a role which work along side a Management Center.
It seems that to access a specific page, we would need to assert the role of the user and the Management Center in which he is assign.
